/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include "../../../../../../../Library/Android/sdk/ndk/21.1.6352462/toolchains/llvm/prebuilt/darwin-x86_64/sysroot/usr/include/jni.h"
/* Header for class com_icandothisallday2021_ndklib_NativeWrapper */

#ifndef _Included_com_icandothisallday2021_ndklib_NativeWrapper
#define _Included_com_icandothisallday2021_ndklib_NativeWrapper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_icandothisallday2021_ndklib_NativeWrapper
 * Method:    nativeSum
 * Signature: (II)I
 */
extern "C" JNIEXPORT jint JNICALL Java_com_icandothisallday2021_ndklib_NativeWrapper_nativeSum
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
