/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_icandothisallday2021_ndklib_NativeWrapper */

#ifndef _Included_com_icandothisallday2021_ndklib_NativeWrapper
#define _Included_com_icandothisallday2021_ndklib_NativeWrapper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_icandothisallday2021_ndklib_NativeWrapper
 * Method:    nativeSum
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_icandothisallday2021_ndklib_NativeWrapper_nativeSum
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_icandothisallday2021_ndklib_NativeWrapper
 * Method:    nativeString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_icandothisallday2021_ndklib_NativeWrapper_nativeString
  (JNIEnv *, jobject);

JNIEXPORT jfloatArray JNICALL Java_com_icandothisallday2021_ndklib_NativeWrapper_nativeArray
        (JNIEnv *, jobject,jfloatArray jfloatArray1);

#ifdef __cplusplus
}
#endif
#endif
